const tiffinServices = [
    {
        src:"../assets/imgs/ifood.jpg",
        key:"1",
        alt:"service1",
        title:"iFood",
        location:"Karanpur,Dehradun",
        rating:4,
        mon_bfast:"Dosa with Sambhar and Chutney.",
        mon_lunch:"Arhar Dal, Bhindi, Roti, Rice, Salad, Achar.",
        mon_dinner:"Lauki Kofta, Aloo Gobhi, Roti, Rice, Salad, Achar",
        tue_bfast:"Poha",
        tue_lunch:"Tamatar Aloo, Raita, Roti, Rice, Salad, Achar.",
        tue_dinner:"Chana Dal, Mixveg, Roti, Rice, Salad, Achar.",
        wed_bfast:"Aloo Parantha with Achar and sweet Yogurt",
        wed_lunch:"Arhar Dal, Baingan Bharta, Roti, Rice, Salad, Achar.",
        wed_dinner:"Egg Curry, Roti, Rice, Salad, Achar.",
        thu_bfast:"Aloo Poori",
        thu_lunch:"Masoor Dal, Mutter Mushroom veg, Roti, Rice, Salad.",
        thu_dinner:"Chole Masala, Gobhi, Roti, Rice, Salad, Achar.",
        fri_bfast:"Idli with Sambhar and Chutney.",
        fri_lunch:"Dal, Cabbage Subzi, Roti, Rice, Salad, Achar.",
        fri_dinner:"Soyabean Aloo, Baingan aloo, Roti, Rice, Salad, Achar.",
        sat_bfast:"Vada Sambhar.",
        sat_lunch:"Mix dal, Methi aloo, Roti, Rice, Salad, Achar.",
        sat_dinner:"Rajma Masala, Roti, Rice, Salad, Achar.",
        sun_bfast:"Chowmein",
        sun_lunch:"Chole Bhature",
        sun_dinner:"Shahi Paneer, Roti, Rice, Salad, Sweet",
        desc:"Lunch Time: 12pm to 1pm; Dinner Time: 7pm to 8pm. ",
        contact:"7055571588",
        price:"Rs 100,150,200(bfast,lunch,dinner)."
    },
    {
        src:"../assets/imgs/mako.jpg",
        key:"2",
        alt:"service2",
        title:"Mako Tiffin Services",
        location:"Johri Gaon,Jakhan,Dehradun",
        rating:4.5,
        mon_bfast:"Dosa with Sambhar and Chutney.",
        mon_lunch:"Arhar Dal, Bhindi, Roti, Rice, Salad, Achar.",
        mon_dinner:"Lauki Kofta, Aloo Gobhi, Roti, Rice, Salad, Achar",
        tue_bfast:"Poha",
        tue_lunch:"Tamatar Aloo, Raita, Roti, Rice, Salad, Achar.",
        tue_dinner:"Chana Dal, Mixveg, Roti, Rice, Salad, Achar.",
        wed_bfast:"Aloo Parantha with Achar and sweet Yogurt",
        wed_lunch:"Arhar Dal, Baingan Bharta, Roti, Rice, Salad, Achar.",
        wed_dinner:"Egg Curry, Roti, Rice, Salad, Achar.",
        thu_bfast:"Aloo Poori",
        thu_lunch:"Masoor Dal, Mutter Mushroom veg, Roti, Rice, Salad.",
        thu_dinner:"Chole Masala, Gobhi, Roti, Rice, Salad, Achar.",
        fri_bfast:"Idli with Sambhar and Chutney.",
        fri_lunch:"Dal, Cabbage Subzi, Roti, Rice, Salad, Achar.",
        fri_dinner:"Soyabean Aloo, Baingan aloo, Roti, Rice, Salad, Achar.",
        sat_bfast:"Vada Sambhar.",
        sat_lunch:"Mix dal, Methi aloo, Roti, Rice, Salad, Achar.",
        sat_dinner:"Rajma Masala, Roti, Rice, Salad, Achar.",
        sun_bfast:"Chowmein",
        sun_lunch:"Chole Bhature",
        sun_dinner:"Shahi Paneer, Roti, Rice, Salad, Sweet",
        desc:"Lunch Time: 12pm to 1pm; Dinner Time: 7pm to 8pm. ",
        contact:"9410169200",
        price:"Rs 2500 for 1year"
    },
    {
        src:"../assets/imgs/shailja.jpg",
        key:"3",
        alt:"service3",
        title:"Shailja",
        location:"B/20,Block 2,Near DAV College,Dehradun",
        rating:3,
        mon_bfast:"Dosa with Sambhar and Chutney.",
        mon_lunch:"Arhar Dal, Bhindi, Roti, Rice, Salad, Achar.",
        mon_dinner:"Lauki Kofta, Aloo Gobhi, Roti, Rice, Salad, Achar",
        tue_bfast:"Poha",
        tue_lunch:"Tamatar Aloo, Raita, Roti, Rice, Salad, Achar.",
        tue_dinner:"Chana Dal, Mixveg, Roti, Rice, Salad, Achar.",
        wed_bfast:"Aloo Parantha with Achar and sweet Yogurt",
        wed_lunch:"Arhar Dal, Baingan Bharta, Roti, Rice, Salad, Achar.",
        wed_dinner:"Egg Curry, Roti, Rice, Salad, Achar.",
        thu_bfast:"Aloo Poori",
        thu_lunch:"Masoor Dal, Mutter Mushroom veg, Roti, Rice, Salad.",
        thu_dinner:"Chole Masala, Gobhi, Roti, Rice, Salad, Achar.",
        fri_bfast:"Idli with Sambhar and Chutney.",
        fri_lunch:"Dal, Cabbage Subzi, Roti, Rice, Salad, Achar.",
        fri_dinner:"Soyabean Aloo, Baingan aloo, Roti, Rice, Salad, Achar.",
        sat_bfast:"Vada Sambhar.",
        sat_lunch:"Mix dal, Methi aloo, Roti, Rice, Salad, Achar.",
        sat_dinner:"Rajma Masala, Roti, Rice, Salad, Achar.",
        sun_bfast:"Chowmein",
        sun_lunch:"Chole Bhature",
        sun_dinner:"Shahi Paneer, Roti, Rice, Salad, Sweet",
        desc:"Lunch Time: 12pm to 1pm; Dinner Time: 7pm to 8pm. ",
        contact:"8449900990",
        price:"Rs 80/- per meal."
    },
    {
        src:"../assets/imgs/common.jpg",
        key:"4",
        alt:"service4",
        title:"Mayuri Tiffin Service",
        location:"Jakhan,Dehradun",
        rating:4,
        mon_bfast:"Dosa with Sambhar and Chutney.",
        mon_lunch:"Arhar Dal, Bhindi, Roti, Rice, Salad, Achar.",
        mon_dinner:"Lauki Kofta, Aloo Gobhi, Roti, Rice, Salad, Achar",
        tue_bfast:"Poha",
        tue_lunch:"Tamatar Aloo, Raita, Roti, Rice, Salad, Achar.",
        tue_dinner:"Chana Dal, Mixveg, Roti, Rice, Salad, Achar.",
        wed_bfast:"Aloo Parantha with Achar and sweet Yogurt",
        wed_lunch:"Arhar Dal, Baingan Bharta, Roti, Rice, Salad, Achar.",
        wed_dinner:"Egg Curry, Roti, Rice, Salad, Achar.",
        thu_bfast:"Aloo Poori",
        thu_lunch:"Masoor Dal, Mutter Mushroom veg, Roti, Rice, Salad.",
        thu_dinner:"Chole Masala, Gobhi, Roti, Rice, Salad, Achar.",
        fri_bfast:"Idli with Sambhar and Chutney.",
        fri_lunch:"Dal, Cabbage Subzi, Roti, Rice, Salad, Achar.",
        fri_dinner:"Soyabean Aloo, Baingan aloo, Roti, Rice, Salad, Achar.",
        sat_bfast:"Vada Sambhar.",
        sat_lunch:"Mix dal, Methi aloo, Roti, Rice, Salad, Achar.",
        sat_dinner:"Rajma Masala, Roti, Rice, Salad, Achar.",
        sun_bfast:"Chowmein",
        sun_lunch:"Chole Bhature",
        sun_dinner:"Shahi Paneer, Roti, Rice, Salad, Sweet",
        desc:"Lunch Time: 12pm to 1pm; Dinner Time: 7pm to 8pm. ",
        contact:"8384890379",
        price:"Rs 50/- per meal."
    },
    {
        src:"../assets/imgs/common.jpg",
        key:"5",
        alt:"service5",
        title:"Manseer",
        location:"Jakhan,Dehradun",
        rating:4,
        mon_bfast:"Dosa with Sambhar and Chutney.",
        mon_lunch:"Arhar Dal, Bhindi, Roti, Rice, Salad, Achar.",
        mon_dinner:"Lauki Kofta, Aloo Gobhi, Roti, Rice, Salad, Achar",
        tue_bfast:"Poha",
        tue_lunch:"Tamatar Aloo, Raita, Roti, Rice, Salad, Achar.",
        tue_dinner:"Chana Dal, Mixveg, Roti, Rice, Salad, Achar.",
        wed_bfast:"Aloo Parantha with Achar and sweet Yogurt",
        wed_lunch:"Arhar Dal, Baingan Bharta, Roti, Rice, Salad, Achar.",
        wed_dinner:"Egg Curry, Roti, Rice, Salad, Achar.",
        thu_bfast:"Aloo Poori",
        thu_lunch:"Masoor Dal, Mutter Mushroom veg, Roti, Rice, Salad.",
        thu_dinner:"Chole Masala, Gobhi, Roti, Rice, Salad, Achar.",
        fri_bfast:"Idli with Sambhar and Chutney.",
        fri_lunch:"Dal, Cabbage Subzi, Roti, Rice, Salad, Achar.",
        fri_dinner:"Soyabean Aloo, Baingan aloo, Roti, Rice, Salad, Achar.",
        sat_bfast:"Vada Sambhar.",
        sat_lunch:"Mix dal, Methi aloo, Roti, Rice, Salad, Achar.",
        sat_dinner:"Rajma Masala, Roti, Rice, Salad, Achar.",
        sun_bfast:"Chowmein",
        sun_lunch:"Chole Bhature",
        sun_dinner:"Shahi Paneer, Roti, Rice, Salad, Sweet",
        desc:"Lunch Time: 12pm to 1pm; Dinner Time: 7pm to 8pm. ",
        contact:"7310707186",
        price:"Rs 2800(three meals),2200(two meals)."
    },
    {
        src:"../assets/imgs/common.jpg",
        key:"6",
        alt:"service6",
        title:"True Meal",
        location:"76,Doon Vihar,Jakhan,Dehradun",
        rating:4.5,
        mon_bfast:"Dosa with Sambhar and Chutney.",
        mon_lunch:"Arhar Dal, Bhindi, Roti, Rice, Salad, Achar.",
        mon_dinner:"Lauki Kofta, Aloo Gobhi, Roti, Rice, Salad, Achar",
        tue_bfast:"Poha",
        tue_lunch:"Tamatar Aloo, Raita, Roti, Rice, Salad, Achar.",
        tue_dinner:"Chana Dal, Mixveg, Roti, Rice, Salad, Achar.",
        wed_bfast:"Aloo Parantha with Achar and sweet Yogurt",
        wed_lunch:"Arhar Dal, Baingan Bharta, Roti, Rice, Salad, Achar.",
        wed_dinner:"Egg Curry, Roti, Rice, Salad, Achar.",
        thu_bfast:"Aloo Poori",
        thu_lunch:"Masoor Dal, Mutter Mushroom veg, Roti, Rice, Salad.",
        thu_dinner:"Chole Masala, Gobhi, Roti, Rice, Salad, Achar.",
        fri_bfast:"Idli with Sambhar and Chutney.",
        fri_lunch:"Dal, Cabbage Subzi, Roti, Rice, Salad, Achar.",
        fri_dinner:"Soyabean Aloo, Baingan aloo, Roti, Rice, Salad, Achar.",
        sat_bfast:"Vada Sambhar.",
        sat_lunch:"Mix dal, Methi aloo, Roti, Rice, Salad, Achar.",
        sat_dinner:"Rajma Masala, Roti, Rice, Salad, Achar.",
        sun_bfast:"Chowmein",
        sun_lunch:"Chole Bhature",
        sun_dinner:"Shahi Paneer, Roti, Rice, Salad, Sweet",
        desc:"Lunch Time: 12pm to 1pm; Dinner Time: 7pm to 8pm. ",
        contact:"8218043478",
        price:"Rs 70/- per meal."
    },
    {
        src:"../assets/imgs/common.jpg",
        key:"7",
        alt:"service7",
        title:"Second Mother Tiffin Service",
        location:"Khurbura Mohalla, Near SGRR Public School,Dehradun",
        rating:5,
        mon_bfast:"Dosa with Sambhar and Chutney.",
        mon_lunch:"Arhar Dal, Bhindi, Roti, Rice, Salad, Achar.",
        mon_dinner:"Lauki Kofta, Aloo Gobhi, Roti, Rice, Salad, Achar",
        tue_bfast:"Poha",
        tue_lunch:"Tamatar Aloo, Raita, Roti, Rice, Salad, Achar.",
        tue_dinner:"Chana Dal, Mixveg, Roti, Rice, Salad, Achar.",
        wed_bfast:"Aloo Parantha with Achar and sweet Yogurt",
        wed_lunch:"Arhar Dal, Baingan Bharta, Roti, Rice, Salad, Achar.",
        wed_dinner:"Egg Curry, Roti, Rice, Salad, Achar.",
        thu_bfast:"Aloo Poori",
        thu_lunch:"Masoor Dal, Mutter Mushroom veg, Roti, Rice, Salad.",
        thu_dinner:"Chole Masala, Gobhi, Roti, Rice, Salad, Achar.",
        fri_bfast:"Idli with Sambhar and Chutney.",
        fri_lunch:"Dal, Cabbage Subzi, Roti, Rice, Salad, Achar.",
        fri_dinner:"Soyabean Aloo, Baingan aloo, Roti, Rice, Salad, Achar.",
        sat_bfast:"Vada Sambhar.",
        sat_lunch:"Mix dal, Methi aloo, Roti, Rice, Salad, Achar.",
        sat_dinner:"Rajma Masala, Roti, Rice, Salad, Achar.",
        sun_bfast:"Chowmein",
        sun_lunch:"Chole Bhature",
        sun_dinner:"Shahi Paneer, Roti, Rice, Salad, Sweet",
        desc:"Lunch Time: 12pm to 1pm; Dinner Time: 7pm to 8pm. ",
        contact:"8077436481",
        price:"Rs 300 for 1 year."
    },
    {
        src:"../assets/imgs/common.jpg",
        key:"8",
        alt:"service8",
        title:"Ghar ki rasoi",
        location:"73/1,Doon Vihar,Lane 1,Jakhan,Dehradun",
        rating:5,
        mon_bfast:"Dosa with Sambhar and Chutney.",
        mon_lunch:"Arhar Dal, Bhindi, Roti, Rice, Salad, Achar.",
        mon_dinner:"Lauki Kofta, Aloo Gobhi, Roti, Rice, Salad, Achar",
        tue_bfast:"Poha",
        tue_lunch:"Tamatar Aloo, Raita, Roti, Rice, Salad, Achar.",
        tue_dinner:"Chana Dal, Mixveg, Roti, Rice, Salad, Achar.",
        wed_bfast:"Aloo Parantha with Achar and sweet Yogurt",
        wed_lunch:"Arhar Dal, Baingan Bharta, Roti, Rice, Salad, Achar.",
        wed_dinner:"Egg Curry, Roti, Rice, Salad, Achar.",
        thu_bfast:"Aloo Poori",
        thu_lunch:"Masoor Dal, Mutter Mushroom veg, Roti, Rice, Salad.",
        thu_dinner:"Chole Masala, Gobhi, Roti, Rice, Salad, Achar.",
        fri_bfast:"Idli with Sambhar and Chutney.",
        fri_lunch:"Dal, Cabbage Subzi, Roti, Rice, Salad, Achar.",
        fri_dinner:"Soyabean Aloo, Baingan aloo, Roti, Rice, Salad, Achar.",
        sat_bfast:"Vada Sambhar.",
        sat_lunch:"Mix dal, Methi aloo, Roti, Rice, Salad, Achar.",
        sat_dinner:"Rajma Masala, Roti, Rice, Salad, Achar.",
        sun_bfast:"Chowmein",
        sun_lunch:"Chole Bhature",
        sun_dinner:"Shahi Paneer, Roti, Rice, Salad, Sweet",
        desc:"Lunch Time: 12pm to 1pm; Dinner Time: 7pm to 8pm. ",
        contact:"7565598188",
        price:"Rs 120/- per meal."
    }








];

export default tiffinServices;